### ISSUE TITLE
Auto-format code

### ISSUE THREAD

**Issue by gschivley** [GenXProject/GenX.jl#143]
The GenX codebase has lots of lines that are much longer than 80/92 characters. Many projects (python, julia, etc) use auto formatters to ensure that code is always formatted in a consistent way. For example, PowerSystems.jl has a github action that [checks all pull requests](https://github.com/NREL-SIIP/PowerSystems.jl/blob/master/.github/workflows/format-check.yml) for formatting using [JuliaFormatter.jl](https://github.com/domluna/JuliaFormatter.jl). I do the same with Black for PRs to PowerGenome. The advantages of auto formatting code are that 1) lines don't get too long and 2) everything in the codebase has the same visual style. Respecting line length makes it easier to view two files side-by-side. A uniform visual style makes it easier to read the code without forcing everyone to learn/follow a set of code guidelines.

**Comment by gschivley** [comment]
> My worry about the actual implementation would be that it would make git blame harder across the jump - or is there a flag to ignore certain commits?

Looks like there is [a way to do this](https://tekin.co.uk/2020/09/ignore-linting-and-formatting-commits-when-running-git-blame) (at least locally). It doesn't work on GitHub but there is an [active request for the feature](https://github.com/github/feedback/discussions/5033).

>I would love to see this implemented, perhaps just after bringing the codebase "back together", like if/when we merge back main and Dev before a next minor release. Otherwise I would imagine it would make things more difficult to merge two branches together.

Agree that it's best done with or after a merge/PR.

>As a related point, at least some of the long lines are long because they have complex interior expressions, not simply because they're, say, a long list. These should probably be rewritten or functionalized, not just formatted.

I don't disagree.

For anyone who isn't sure why it helps to auto-format the code, one advantage is that it changes this view
![image](https://user-images.githubusercontent.com/10373332/154522691-fddca7d7-d2bf-47c6-a41c-7c7eb01dd6b1.png)

to this

![image](https://user-images.githubusercontent.com/10373332/154523295-7e48935e-881a-424c-a51c-2a567eefc9ab.png)


Because the formatted code conforms to maximum line lengths (the default is 92) I can easily have side-by-side code windows. It also removes all personal choice about if statements should look like this

```
        if v println("Pre-removal: ", names(ModifiedDataNormalized)) end
```
or this
```
        if v
            println("Pre-removal: ", names(ModifiedDataNormalized))
        end
```

The benefit is that code looks the same everywhere without having to convince everyone to adopt the same style.

**Comment by sambuddhac** [comment]
PR #673 addresses this.

**Comment by sambuddhac** [comment]
Addressed on release branch
