### ISSUE TITLE
TDR requires None column in Fuels_data

### ISSUE THREAD

**Issue by gmantegna** [GenXProject/GenX.jl#552]
Currently, the TDR algorithm throws an error if Fuels_data.csv does not have a None column (for resources that do not use fuel). This should not be required, as GenX itself does not require this column.

cc @cfe316

**Comment by cfe316** [comment]
@lbonaldo Presumably after loading it from the csv file, TDR only interacts with Fuels_data as a dataframe. We could abstract this to separate the steps of 

1. Load raw data from a file
2. Preprocess data, i.e. add a None column
3. (optionally) parse to separate the time series itself from the co2-per-mmbtu numbers.
4. Present the data to the client function.

**Comment by lbonaldo** [comment]
Yes, I think we should have that kind of abstraction for all the inputs. Let me work on that.

**Comment by lbonaldo** [comment]
#720 fixed this issue on develop.
