### ISSUE TITLE
Multistage Costs do not apply OPEXMULT discount factor to UnmetPolicyPenalty

### ISSUE THREAD

**Issue by filippopecci** [GenXProject/GenX.jl#623]
On line 42, function [write_multi_stage_cost!](https://github.com/GenXProject/GenX/blob/main/src/multi_stage/write_multi_stage_costs.jl) applies discount factor to all OPEX costs, but misses cUnmetPolicyPenalty.

**Comment by sambuddhac** [comment]
> On line 42, function [write_multi_stage_cost!](https://github.com/GenXProject/GenX/blob/main/src/multi_stage/write_multi_stage_costs.jl) applies discount factor to all OPEX costs, but misses cUnmetPolicyPenalty.

@filippopecci is this still referring to the `develop` branch or the `main` branch?

**Comment by filippopecci** [comment]
@sambuddhac it's on both branches
