### ISSUE TITLE
[Bug]:  wrong contraint expression in reserves_contingency!(EP::Model, inputs::Dict, setup::Dict) doc

### ISSUE THREAD

**Issue by mrchamanbaz** [GenXProject/GenX.jl#689]
### Bug description

Hi
There is a typo in the reserves_contingency help file. There is nothing wrong with the actual constraint, but there is a typo in the latex expression explaining the constraint. 

The following expression is wrong and does not capture the actual constraint in the code:
\begin{aligned}
	&Contingency \geq \Omega^{size}_{y,z} \times \alpha^{Contingency,Aux}_{y,z} & \forall y \in \mathcal{UC}, z \in \mathcal{Z}\\
	&\alpha^{Contingency,Aux}_{y,z} \leq \Delta^{\text{total}}_{y,z} & \forall y \in \mathcal{UC}, z \in \mathcal{Z}\\
	&\alpha^{Contingency,Aux}_{y,z} \geq M_y \times \Delta^{\text{total}}_{y,z} & \forall y \in \mathcal{UC}, z \in \mathcal{Z}\\
\end{aligned}

The correct expression is:
\begin{aligned}
	&Contingency \geq \Omega^{size}_{y,z} \times \alpha^{Contingency,Aux}_{y,z} & \forall y \in \mathcal{UC}, z \in \mathcal{Z}\\
	&\alpha^{Contingency,Aux}_{y,z} \leq \Delta^{\text{total}}_{y,z} & \forall y \in \mathcal{UC}, z \in \mathcal{Z}\\
	& \Delta^{\text{total}}_{y,z}  \leq M_y  \times \alpha^{Contingency,Aux}_{y,z}  & \forall y \in \mathcal{UC}, z \in \mathcal{Z}\\
\end{aligned}

The same problem exists in Dynamic commitment-based contingency Option 3. 

### Environment and Version

Windows OS, Julia 1.10.2

**Comment by lbonaldo** [comment]
Thank you, @mrchamanbaz, for opening this issue. Following your suggestion, we've updated the docstring, and this change will be incorporated into the upcoming release.
