### ISSUE TITLE
GenX Documentation [Bug]: 

### ISSUE THREAD

**Issue by MADNANTARRAR** [GenXProject/GenX.jl#697]
### Bug description

In GenX documentation, the content in tutorial 3 about K means is incomplete and missing, please review it. I have attached picture of it here. 
![k means error in conetnt](https://github.com/GenXProject/GenX.jl/assets/162075463/e318deb4-91ec-4759-9cfa-fa143909f9be)
Thanks 

### Environment and Version

Windows, Julia version, GenX version 0.4

### Relevant error messages

```shell
In GenX documentation, the content in tutorial 3 about K means is incomplete and missing, please review it. Thanks
```

**Comment by lbonaldo** [comment]
Thank you, @MADNANTARRAR, for opening this issue. The [documentation](https://genxproject.github.io/GenX.jl/dev/Tutorials/Tutorial_3_K-means_time_domain_reduction/) has now been updated.

**Comment by MADNANTARRAR** [comment]
Thanks !

________________________________
