### ISSUE TITLE
[Question]: Modelling Capacity Reserve Margin for Storage Resources

### ISSUE THREAD

**Issue by go3703** [GenXProject/GenX.jl#726]
### Question

The overall contribution of storage devices to the system's capacity reserve margin includes actual and virtual charge and discharge terms. The actual charge and discharge terms are indexed by "y∈O" and the virtual charge and discharge terms are indexed by "o∈O." Are there any differences between the two? Also, the derating factor ϵ multiplies the net discharge (accounting for both virtual charge and discharge), rather than the load in each time step. Can you explain why this is the case? I thought ϵ should represent a fraction of the load. Heres the link to the reference page for this issue: https://genxproject.github.io/GenX.jl/dev/Model_Reference/Resources/storage/

**Comment by gmantegna** [comment]
Hi! Thanks for your question. The storage virtual discharge formulation is described in more detail in the PDF attached to PR #475 . In short, the difference is that the virtual charge and discharge represents the charging and discharging behavior a storage device "could" have done if needed, which allows it to contribute to the capacity reserve margin (which requires surplus capacity on top of peak load) in the same way a thermal resource can.
