### ISSUE TITLE
[Bug]: VRE_STOR asks for both wind and solar variability data when there is only solar or wind components in VRE_STOR.

### ISSUE THREAD

**Issue by qluo0320github** [GenXProject/GenX.jl#727]
### Bug description

I only have WIND component in VRE_STOR but GenX still asks for "Vre_and_stor_solar_variability.csv".

The error is caused by the lack of checking the existence of "WIND" or "SOLAR" component in load_vre_stor_variability.jl

### Environment and Version

GenX 0.4

**Comment by lbonaldo** [comment]
Thank you, @qluo0320github, for opening this issue. It is being resolved by #728 on develop.
