### ISSUE TITLE
[Bug]: Examples 2 and 6 have Hydro_Energy_to_Power_Ratio in Thermal.csv

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX.jl#737]
### Bug description

See
`2_three_zones_w_electrolyzer/resources/Thermal.csv`
and
`6_three_zones_w_multistage/inputs/inputs_p*/resources/Thermal.csv`

All four of these files have the column `Hydro_Energy_to_Power_Ratio`, but should not.

### Environment and Version

develop

**Comment by lbonaldo** [comment]
Resolved by https://github.com/GenXProject/GenX.jl/pull/738 on develop.
