### ISSUE TITLE
[Bug]: Typos: HydrogenMimimumProduction

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX.jl#740]
### Bug description

`HydrogenMimimumProduction` -> `HydrogenMinimumProduction`

Also appearing here
```
./load_inputs/load_energy_share_requirement.jl:4:Read input parameters related to mimimum energy share requirement constraints
./load_inputs/load_minimum_capacity_requirement.jl:4:Read input parameters related to mimimum capacity requirement constraints
```

I'm labeling this as a bug since it's a user-accessible setting.

### Environment and Version

develop

**Comment by lbonaldo** [comment]
Resolved by https://github.com/GenXProject/GenX.jl/pull/746 on develop.
