### ISSUE TITLE
[Feature]: remove vZERO cruft

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX.jl#741]
### Feature description

`vZERO`, a JuMP variable which is always zero, was necessary in a few places in early versions of GenX/JuMP. It is not necessary any longer. As cruft, it should be removed.

### Motivation

Removing useless code makes the rest more readable.

**Comment by lbonaldo** [comment]
Resolved by https://github.com/GenXProject/GenX.jl/pull/742 on develop.
