### ISSUE TITLE
[Documentation]: Typos in Model_notation.md

### ISSUE THREAD

**Issue by cfe316** [GenXProject/GenX.jl#761]
### Bug description

In `model_notation.md`:

- `\mathcal{X}` ($`\mathcal{X}`$) is used for unit commitment startup decisions instead of `\chi` ($`\chi`$).
- `v` ($`v`$) is used for unit commitment state instead of `\nu` ($`\nu`$).

This would make the notation consistent with that in `thermal_commit.jl` and other places.

### Environment and Version

n/a

**Comment by lbonaldo** [comment]
Thanks @cfe316 for fixing these typos. I'm closing this issue as resolved.
