### ISSUE TITLE
[Bug]: Tutorials Power.csv Plot

### ISSUE THREAD

**Issue by M0-Adnan** [GenXProject/GenX.jl#782]
### Bug description

![image](https://github.com/user-attachments/assets/30231de3-5057-4939-9c4b-66250199cb08)

Hi,

In the tutorial section, it is mentioned that the demand data used for plotting power.csv is taken from the system folder. However, this is not accurate. If someone is performing TDR, GenX creates a new folder named TDR_results. Inside this folder, there is a Demand_data.csv file, which is the actual demand data used to run the case. Therefore, the Demand_data.csv file from the TDR_results folder should be used for plotting (as is the case for given example), not the one from the system folder. Thank you

### Environment and Version

MacOS, Juliac1.10

**Comment by lbonaldo** [comment]
Hello @M0-Adnan, you’re right—this is correct. I’ll push a fix as soon as possible.

**Comment by lbonaldo** [comment]
Thank you @M0-Adnan for opening this issue. It's now resolved in the `develop` branch and will be included in the upcoming release. We've also updated the corresponding notebook in the GenX-Tutorials [repository](https://github.com/GenXProject/GenX-Tutorials).

**Comment by M0-Adnan** [comment]
Thanks 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
