### ISSUE TITLE
[Bug]: CapRes flag for transmission lines does not appear to do anything

### ISSUE THREAD

**Issue by gmantegna** [GenXProject/GenX.jl#784]
### Bug description

In transmission.jl, the [code for adding transmission lines to the CRM constraint](https://github.com/GenXProject/GenX.jl/blob/73ab92d78fef9d8a934f3bb20b74795096da3ca9/src/model/core/transmission/transmission.jl#L162) does not appear to take into account whether a transmission line is supposed to be included in a CRM constraint as given by the CapRes_* column. The documentation says this column is required to tell the model whether a line is included in the constraint, but I do not see this column being read in or used anywhere. 

### Environment and Version

MacOS, julia 1.10, GenX 0.4

**Comment by gmantegna** [comment]
I should note that it's possible this is just an issue with the documentation. Maybe this column is supposed to actually not exist with the current version of the code.

**Comment by lbonaldo** [comment]
Closing this issue as resolved.
