### ISSUE TITLE
[Question]: Binary parameter ‘TimeDomainReduction’

### ISSUE THREAD

**Issue by WeiAi-Energy** [GenXProject/GenX.jl#786]
### Question

In **Tutorial 1**, it says that '_For example, to use TimeDomainReduction, you would set its parameter to 0_', but in the table **Model structure related settings parameters**, it says that '_TimeDomainReduction: 0 = Use the data in the main case folder; do not perform clustering_', so it seems there is a contradictory. Which one is correct?

**Comment by lbonaldo** [comment]
I’m closing this issue as resolved. Please feel free to reopen it if further discussion is needed.
